#!/usr/bin/env bash
# Usage: hr clone [-f] <repo>
#
# Summary: Clone down an HR project into $SOURCE_DIR
#
# Help: Clone down an HR project into $SOURCE_DIR. If you provide
# the "-f" flag, the repository will be redownloaded.
#
# Note: This command requires $SOURCE_DIR to be set.

if [ -z "$SOURCE_DIR" ]; then
  echo "Error: \$SOURCE_DIR not set" >&2
  exit 1
fi

if [ "$1" = "--complete" ]; then
  echo "-f"
  [ -f "$HOME/.repos" ] && cat "$HOME/.repos"
  exit 0
fi

if [ -z "$1" ]; then
  {
    hr-help clone
    echo
    echo "ERROR: please provide a repo"
  } >&2
  exit 1
fi

if [ "x-f" = "x$1" ]; then
  shift
  rm -rf "$SOURCE_DIR/`basename $1 .git`"
fi

basename="`basename $1 .git`"
path="$SOURCE_DIR/$basename"
new=
url=

case "$1" in
  *:*) url="$1" ;;
  */*) url="git@github.com:$1.git" ;;
  *)   url="git@github.com:hashrocket/$1.git" ;;
esac

if [ ! -d "$path" ]; then
  new=1
fi

setup_git_hooks() {
  cd "$path"
  if [ ! -f .git/hooks/post-rewrite ]; then
    cat > .git/hooks/post-rewrite <<EOS
#!/bin/sh

GIT_DIR="\$(dirname "\$(dirname "\$0")")"
export GIT_DIR

case "\$1" in
  rebase) exec "\$GIT_DIR/hooks/post-merge" 0 rebase ;;
esac
EOS
  fi
  if [ ! -f .git/hooks/pre-commit ]; then
    echo '#!/bin/sh' > .git/hooks/pre-commit
    echo 'git diff --exit-code --cached -- Gemfile Gemfile.lock >/dev/null || bundle check' >> .git/hooks/pre-commit
  fi
  if [ ! -f .git/hooks/ctags ]; then
    echo '#!/bin/sh' > .git/hooks/ctags
    echo 'rm -f .git/tags' >> .git/hooks/ctags
    echo 'ctags --tag-relative -f .git/tags --exclude=.git --exclude=db --exclude=public/uploads --exclude=vendor --exclude=tmp --languages=-javascript,html,sql -R' >> .git/hooks/ctags
    chmod +x .git/hooks/ctags
    for basename in post-checkout post-commit post-merge; do
      echo '#!/bin/sh' > .git/hooks/$basename
      echo '$GIT_DIR/hooks/ctags >/dev/null 2>&1 &' >> .git/hooks/$basename
      chmod +x .git/hooks/$basename
    done
    .git/hooks/ctags
  fi
  echo 'if command -v hookup >/dev/null; then' >> .git/hooks/post-checkout
  echo '  hookup post-checkout "$@"' >> .git/hooks/post-checkout
  echo "fi" >> .git/hooks/post-checkout
}

setup_bin_path() {
  cd "$path"
  ln -sf ../bin .git
  mkdir -p .git/safe
}

clone_if_necessary() {
  local example
  if [ -n "$new" ]; then
    git clone "$url" "$path" || return 1
    for example in "$path"/config/*.example.yml; do
      cp "$example" "${example%.example.yml}.yml"
    done 2>/dev/null
    if [ -f "$path/.rvmrc" ] && command -v __rvm_trust_rvmrc >/dev/null; then
      __rvm_trust_rvmrc "$path/.rvmrc"
    fi
  fi
  return 0
}

script_setup() {
  if [ -n "$new" -a -x script/setup ]; then
    script/setup
  elif [ -n "$new" -a -x bin/setup ]; then
    bin/setup
  fi
}

setup_git_submodules() {
  cd "$path"
  git submodule init
  git submodule update
  cd ..
}

hclone() {
  clone_if_necessary || return 1
  setup_git_submodules
  setup_git_hooks
  setup_bin_path
  script_setup
}

hclone "$@" >&2 && echo && echo "$path"
