#!/usr/bin/env bash
# Usage: hr freethousand [port]
#
# Summary: Kill a process that is listening a port
#
# Help: Don't know where that Rails server is listening? Just freethousand!
# This command takes a port as an argument, otherwise defaulting to 3000.

port="${1:-3000}"
pid="$(lsof -Fp -i tcp:$port | sed 's/p//')"

if [ -n "$pid" ]; then
  echo "Killing process with PID $pid listening on port $port..." >&2
  kill $pid
else
  echo "No process listening on port $port" >&2
  exit 1
fi
