#!/usr/bin/env bash
# Usage: hr source
# Summary: Output source of hr command <command>
# Help: Just run hr source <command>, where <command> is the name of the
# desired hr command.

if [ "$1" = "--complete" ]; then
  exec hr commands
fi

if [ -z "$1" ]; then
  echo "Please provide a command name" >&2
  exit 1
fi

bin="hr-$1"
path="$(which $bin)"

if [ -n "$path" ]; then
  exec cat $path
else
  echo "Could not find command $1" >&2
  exit 1
fi
