#!/usr/bin/env bash
# Usage: hr setup-unicornleap
#
# Summary: Install unicornleap
# Help: Install unicornleap

set -e

brew tap hashrocket/formulas
brew install unicornleap

echo
echo "You're all set!"
