#!/usr/bin/env bash
# Usage: hr setup-pear
#
# Summary: Install pear (for managing paired git authors)
# Help: Install pear (for managing paired git authors)

set -e

brew tap hashrocket/formulas
brew install hashrocket/formulas/pear

echo
echo "You're all set!"
