#!/usr/bin/env bash
# Usage: hr update
# Summary: Update hr and all plugins
# Help: Just run `hr update`

set -e

header() {
  echo -e "\033[33m$1\033[0m"
}

if [ "$1" = "--complete" ]; then
  exec hr-commands
fi

cd $_HR_ROOT/..
header "Updating dotmatrix"
bin/upgrade

shopt -s nullglob

for plugin in "${_HR_ROOT}/plugins"/*/ ; do
  (
    echo
    echo
    name="$(basename $plugin)"
    header "Updating hr plugin $name"
    cd $plugin
    git pull --rebase
  )
done

shopt -u nullglob
