#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

export ORIG_PATH="$PATH"

libexec_path="$(abs_dirname "$0")"
export _HR_ROOT="$(abs_dirname "$libexec_path")"
export _HR_SHARE="$_HR_ROOT/share"

# HR extensions
if [ -n "$HR_LIBEXEC_PATH" ]; then
  export HR_LIBEXEC_PATH=`echo ${HR_LIBEXEC_PATH} | awk -v RS=: -v ORS=: '/^$/ {next} {print}' | sed 's/:*$//'`
  PATH="${HR_LIBEXEC_PATH}:$PATH"
fi

shopt -s nullglob

bin_path=$libexec_path
for plugin_bin in "${_HR_ROOT}/plugins/"*/libexec; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

shopt -u nullglob

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec hr-help
  ;;
* )
  command_path="$(command -v "hr-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "hr: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
