#!/usr/bin/env bash
#
# Usage: hr contributions [<args>]
#
# Summary: Show sorted list of git commit authorship totals
#
# Help: From within a folder tracked by git, run `hr contributions`. The
# output is a sorted list of names and the number of commits they've
# contributed. Any arguments are forwarded to `git log`.
#
# Examples:
# $ hr contributions                      # for entire repo history
# $ hr contributions -n30                 # authorship for last 30 commits
# $ hr contributions --since="last week"

set -e

prog=' BEGIN{ FS=",? and |, "; OFS="" };
END{ for(name in count) print count[name],"|",name; print NR,"|TOTAL"};
{ for(i=1; i<=NF; i++) { count[$i]++; } } '

git log --format="%an" $@ | awk "$prog" | sort -nr | column -t -s '|'
