#!/usr/bin/env bash
set -e

print=""
if [ "$1" = "-" ]; then
  print=1
  shift
fi

shell="$1"
if [ -z "$shell" ]; then
  shell="$(basename "$SHELL")"
fi

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bashrc.local'
    ;;
  zsh )
    profile='~/.zshrc.local'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load hr automatically by adding"
    echo "# the following to ${profile}:"
    echo
    echo "eval \"\$(${_HR_ROOT}/bin/hr init -)\""
    echo
  } >&2

  exit 1
fi

echo "export PATH=\"\${PATH}:${_HR_ROOT}/bin\""

case "$shell" in
bash | zsh )
  echo "source \"${_HR_ROOT}/completions/hr.${shell}\""
  ;;
esac

commands=(`hr commands --sh`)
IFS="|"
cat <<EOS
_hr_wrapper() {
  local command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval \`hr "sh-\$command" "\$@"\`;;
  *)
    command hr "\$command" "\$@";;
  esac
}
EOS

# zsh can't pass argument with aliases, but bash can.
# zsh can have functions with the name being only numbers, but bash can't.
# fix both cases here by letting zsh have a function, and bash have its alias.
case "$shell" in
bash )
  echo "alias hr=_hr_wrapper"
  ;;
zsh )
  echo "hr=_hr_wrapper"
  ;;
esac
