#!/usr/bin/env ruby
# Usage: hr otd
# Summary: Print a random event that happened on this day in history, courtesy
# of Wikipedia.
require 'nokogiri'
require 'open-uri'

def todays_url
  todays_date = Time.now.strftime("%B_%-e")
  "https://en.wikipedia.org/wiki/#{todays_date}"
end

def events
  Nokogiri::HTML(open(todays_url))
    .xpath('//ul')[1]
    .elements
    .collect {|node| node.text.strip}
end

puts "On this day in #{events.sample}"
