#!/usr/bin/env bash

# Delegate to "real" command
cmd="$(hr-clone "$@")"
if [ ! "$?" = "0" ]; then
  exit $?
fi

path="$(echo $cmd | tail -1)"
# Change directories to new repo
if [ -n "$path" ]; then
  echo "cd $path"
fi
