#!/usr/bin/env bash
#
# Usage: hr vimbundles
#
# Summary: Install or update all vim plugins defined in ~/.vimbundle
#
# Help: Running `hr vimbundles` will iterate through the plugins listed in the
# ~/.vimbundle and ~/.vimbundle.local files. If the plugin isn't already in the
# folder, it will be fetched. If it already exists, the latest will be fetched
# from github.
#
# Entries in these manifest files should be in this format:
# githubusername/reponame
#
# Example:
#
# tpope/vim-surround
# tpope/vim-rails
#
# This would fetch both the vim-surround and the vim-rails plugins from the
# corresponding repos on tpope's github account.

if [ "$1" = "--complete" ]; then
  exit
fi

if [ ! -d "$HOME/.vimbundles" ]; then
  BASE="$HOME/.vim/bundle"
else
  BASE="$HOME/.vimbundles"
fi

mkdir -p $BASE

install_from() {
  if [ -r $1 ]; then
    repos="$(cat $1)"
    for repo in $repos; do
      cd $BASE
      dir="$(basename $repo)"
      echo
      if [ -d "$BASE/$dir" ]; then
        echo "Updating $repo"
        cd "$BASE/$dir"
        git pull --rebase
      else
        git clone https://github.com/"$repo".git
      fi
    done
  fi
}

install_from "$HOME/.vimbundle"
install_from "$HOME/.vimbundle.local"
vim -c 'call pathogen#helptags()|q'
